### ISSUE TITLE
Only the default reward is working

### ISSUE THREAD

**Issue by ConfuseN** [astei/SuperbVote#74]
This is my config, I am on the latest paper version. Used a similar config before 1.14.2 had no issues.

https://hastebin.com/tutulexuwa.pl

**Comment by astei** [comment]
Your default reward is the very first reward. Since your rewards don't cascade (in other words, continue running), the other rewards never match and you see this error.

The fix is to move the default reward to the bottom. I have [made this more clear in the documentation](https://github.com/astei/SuperbVote/wiki/Configuration#rewards).
