### ISSUE TITLE
Console spam when placing blocks

### ISSUE THREAD

**Issue by RektedM8** [astei/SuperbVote#86]
https://gyazo.com/d742487752247d4b0fc97a182d01cadd

**Comment by astei** [comment]
Stop using ancient versions of Minecraft.

Anyway, you have the wrong version of SuperbVote. You need 0.5.2-1.12.

**Comment by RektedM8** [comment]
I am using spigt 1.8, I dont think the newer versions are compatible. Also it was working fine 3 weeks ago

**Comment by astei** [comment]
Look at the resource page, which explains it in big text: https://www.spigotmc.org/resources/superbvote.11626/

> **SuperbVote 0.5.2-1.12 is the last version available for Minecraft 1.8-1.12**. No issues will be fixed in it - I don't have the time to maintain old versions!

**Comment by RektedM8** [comment]
I know but it was fine 3 weeks ago to last saturday which is weird. Will just restart the config file from scratch

**Comment by RektedM8** [comment]
https://gyazo.com/8bb932937ae0dce9a7b0bc90e8591bc1

**Comment by RektedM8** [comment]
Thats the new version

**Comment by RektedM8** [comment]
nvm fixed it

**Comment by CM8DoubleCheck** [comment]
I'm having this exact issue and it was fine up until like 2 weeks ago. I haven't changed a thing, all of a sudden it's spamming the console with 
`Could not pass event BlockPlaceEvent to SuperbVote v0.5.4`

I run 1.12.2 because all newer versions are just not compatible with higher player counts from my experience. It's not an option for me at this time to upgrade. I don't want to go through the hassle of changing my voting plugin because I have well over 100 vote entries in my database.
